apiVersion: v1
kind: POD
metadata:
   - name: 3riNginx
   - namespace: 3ri
spec:
   - containers:
      - name: nginx
      - image: nginx:1.14
      
      
apiVersion : apps/v1
kind: Deployment
metadata: 
   - name: nginx deployment
   - namespace: 3ri
spec:
    templates:
      - containers: nginx
         - replicas: 2
         - name: nginx
         - image: nginx: 20
      
      
      
   
